'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Check, Copy } from 'lucide-react';
import { Thought } from '@/lib/types';

interface ShareCardProps {
  realityCheck: string;
  insights: string[];
  thoughts: Thought[];
  emotionScores: number[];
}

export function ShareCard({
  realityCheck,
  insights,
  thoughts,
  emotionScores,
}: ShareCardProps) {
  const [copied, setCopied] = useState(false);
  const peakIntensity = emotionScores.length ? Math.round(Math.max(...emotionScores)) : 0;
  const topThoughts = thoughts.slice(0, 3).map((t) => t.text);

  const shareText = `🌀 My Overthinking Spiral 😅\n\nPeak Intensity: ${peakIntensity}/100\n\nTop Thoughts:\n${topThoughts
    .map((t, idx) => `${idx + 1}. ${t}`)
    .join('\n')}\n\nReality Check:\n${realityCheck}\n\nKey Insights:\n${insights
    .map((i) => `• ${i}`)
    .join('\n')}\n\nGenerated by ThinkSpiral`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  return (
    <Card className="overflow-hidden border-white/10 bg-gradient-to-br from-slate-900/80 via-purple-950/40 to-slate-900/90 p-6 shadow-xl shadow-black/30 backdrop-blur-xl">
      <h3 className="mb-4 text-3xl font-semibold tracking-tight text-slate-100">
        Reality Check & Insights
      </h3>

      <div className="space-y-4">
        <div className="rounded-xl border border-purple-400/30 bg-gradient-to-r from-purple-600/20 via-fuchsia-600/15 to-indigo-600/20 p-4">
          <div className="mb-2 flex items-center justify-between">
            <p className="text-sm font-semibold text-purple-100">My Overthinking Spiral 😅</p>
            <p className="text-lg font-semibold text-pink-200">{peakIntensity}/100</p>
          </div>
          <ul className="space-y-1 text-sm text-slate-200">
            {topThoughts.map((thought, index) => (
              <li key={`${thought}-${index}`} className="line-clamp-1">
                {index + 1}. {thought}
              </li>
            ))}
          </ul>
        </div>

        {/* Reality Check */}
        <div className="rounded-lg border border-slate-700/80 bg-slate-900/60 p-4">
          <div className="mb-2 text-sm font-semibold text-purple-300">
            Reality Check
          </div>
          <p className="text-slate-300">{realityCheck}</p>
        </div>

        {/* Insights */}
        {insights.length > 0 && (
          <div className="rounded-lg border border-slate-700/80 bg-slate-900/60 p-4">
            <div className="mb-3 text-sm font-semibold text-purple-300">
              Key Insights
            </div>
            <ul className="space-y-2">
              {insights.map((insight, index) => (
                <li
                  key={index}
                  className="flex gap-2 text-sm text-slate-300"
                >
                  <span className="text-purple-400">•</span>
                  <span>{insight}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Copy Button */}
        <Button
          onClick={handleCopy}
          variant="outline"
          className="w-full border-purple-400/30 text-purple-100 hover:bg-purple-500/10"
        >
          {copied ? (
            <>
              <Check className="mr-2 h-4 w-4" /> Copied to clipboard!
            </>
          ) : (
            <>
              <Copy className="mr-2 h-4 w-4" /> Copy Insights
            </>
          )}
        </Button>
      </div>
    </Card>
  );
}
