'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Check, Copy } from 'lucide-react';

interface ShareCardProps {
  realityCheck: string;
  insights: string[];
}

export function ShareCard({ realityCheck, insights }: ShareCardProps) {
  const [copied, setCopied] = useState(false);

  const shareText = `🌀 My Overthinking Spiral Analysis:\n\n${realityCheck}\n\nKey Insights:\n${insights.map((i) => `• ${i}`).join('\n')}\n\nGenerated by ThinkSpiral`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  return (
    <Card className="border-slate-700 bg-slate-800/50 p-6 backdrop-blur">
      <h3 className="mb-4 text-lg font-semibold text-slate-100">
        Reality Check & Insights
      </h3>

      <div className="space-y-4">
        {/* Reality Check */}
        <div className="rounded-lg border border-slate-700 bg-slate-900/50 p-4">
          <div className="mb-2 text-sm font-semibold text-purple-300">
            Reality Check
          </div>
          <p className="text-slate-300">{realityCheck}</p>
        </div>

        {/* Insights */}
        {insights.length > 0 && (
          <div className="rounded-lg border border-slate-700 bg-slate-900/50 p-4">
            <div className="mb-3 text-sm font-semibold text-purple-300">
              Key Insights
            </div>
            <ul className="space-y-2">
              {insights.map((insight, index) => (
                <li
                  key={index}
                  className="flex gap-2 text-sm text-slate-300"
                >
                  <span className="text-purple-400">•</span>
                  <span>{insight}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Copy Button */}
        <Button
          onClick={handleCopy}
          variant="outline"
          className="w-full border-slate-600 text-slate-300 hover:bg-slate-700"
        >
          {copied ? (
            <>
              <Check className="mr-2 h-4 w-4" /> Copied to clipboard!
            </>
          ) : (
            <>
              <Copy className="mr-2 h-4 w-4" /> Copy Insights
            </>
          )}
        </Button>
      </div>
    </Card>
  );
}
